spring:
  security:
    oauth2:
      client:
        registration:
          logingov:
            client-id: urn:gov:gsa:openidconnect.profiles:sp:sso:swf_ntc:apollo
            redirect-uri: "{baseUrl}/login/oauth2/code/logingov"
            authorization-grant-type: authorization_code
            scope: openid, email
        provider:
          logingov:
            authorization-uri: https://idp.int.identitysandbox.gov/openid_connect/authorize?acr_values=http://idmanagement.gov/ns/assurance/ial/1
            token-uri: https://idp.int.identitysandbox.gov/api/openid_connect/token
            user-info-uri: https://idp.int.identitysandbox.gov/api/openid_connect/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://idp.int.identitysandbox.gov/api/openid_connect/certs